### ISSUE TITLE
install capybara on storefront

### ISSUE THREAD

**Issue by Enitos** [vuestorefront/vsf-capybara#492]
I have this error 

C:\********\node_modules\@storefront-ui\vue\index.js:2
import SfArrow from "./src/components/atoms/SfArrow/SfArrow.vue";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at r (C:\\********\node_modules\vue-server-renderer\build.dev.js:9315:16)
    at Object.@storefront-ui/vue (webpack:/external "@storefront-ui/vue":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)

**Comment by AishwaryShrivastav** [comment]
Hi, @Enitos, Can you please explain more about this error, in which file are you trying to import the SfArrow ?
I can see that in Capybara, SfArrow is imported and used in o-my-account-order-details.vue and it works perfectly fine!

**Comment by dt2patel** [comment]
Suggestion by Aishwary looks good. Closing issue.
